# Generated by Django 4.2.2 on 2023-07-03 03:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoIdentidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDocumento', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numeroDocumento', models.CharField(max_length=13)),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.nacionalidad')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.sexo')),
                ('tipoDocumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.documentoidentidad')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroLibro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPrestamo', models.DateField()),
                ('diasPrestamo', models.IntegerField()),
                ('entregado', models.BooleanField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.book')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('numeroDocumento', models.CharField(max_length=13)),
                ('books', models.ManyToManyField(to='libro.book')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.nacionalidad')),
                ('sexo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.sexo')),
                ('tipoDocumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libro.documentoidentidad')),
            ],
        ),
    ]
